// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUdWBijbj2UI_k3GH5VZ0hSf7h1XePQ0o',
    appId: '1:258489829851:web:24f0e054e4088dab457ffe',
    messagingSenderId: '258489829851',
    projectId: 'spitch-work',
    authDomain: 'spitch-work.firebaseapp.com',
    storageBucket: 'spitch-work.appspot.com',
    measurementId: 'G-FCC21P84XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjtaO1hRXBJLLcgPVIN9DMsmS46VA8ZI',
    appId: '1:258489829851:android:40f244e66e7fb8c2457ffe',
    messagingSenderId: '258489829851',
    projectId: 'spitch-work',
    storageBucket: 'spitch-work.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4-J4xUGY4FlyD3-pxIHQK-lcj_J7dsg',
    appId: '1:258489829851:ios:64b14bdae352ece6457ffe',
    messagingSenderId: '258489829851',
    projectId: 'spitch-work',
    storageBucket: 'spitch-work.appspot.com',
    androidClientId:
        '258489829851-81am8b4jl2oqb3otp8tquappfrql2saf.apps.googleusercontent.com',
    iosClientId:
        '258489829851-fpe455c3rahs93s4r5jgsa179l6iqehp.apps.googleusercontent.com',
    iosBundleId: 'com.slike.slikeapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg4-J4xUGY4FlyD3-pxIHQK-lcj_J7dsg',
    appId: '1:258489829851:ios:64b14bdae352ece6457ffe',
    messagingSenderId: '258489829851',
    projectId: 'spitch-work',
    storageBucket: 'spitch-work.appspot.com',
    androidClientId:
        '258489829851-81am8b4jl2oqb3otp8tquappfrql2saf.apps.googleusercontent.com',
    iosClientId:
        '258489829851-fpe455c3rahs93s4r5jgsa179l6iqehp.apps.googleusercontent.com',
    iosBundleId: 'com.slike.slikeapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUdWBijbj2UI_k3GH5VZ0hSf7h1XePQ0o',
    appId: '1:258489829851:web:f42b31867d714b17457ffe',
    messagingSenderId: '258489829851',
    projectId: 'spitch-work',
    authDomain: 'spitch-work.firebaseapp.com',
    storageBucket: 'spitch-work.appspot.com',
    measurementId: 'G-XMZLS5T0SJ',
  );
}
